DROP DATABASE vwserver;
CREATE DATABASE vwserver DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE vwserver;

CREATE TABLE displays (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NULL DEFAULT NULL,
	segment_num_height INT NULL DEFAULT NULL,
	segment_num_width INT NULL DEFAULT NULL,
	segment_height INT NULL DEFAULT NULL,
	segment_width INT NULL DEFAULT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY uk_name(name)
);

CREATE TABLE hardware (
	id BIGINT NOT NULL AUTO_INCREMENT,
	active BOOLEAN NOT NULL DEFAULT 0,
	model_name VARCHAR(32) NULL DEFAULT NULL,
	display_id BIGINT NULL DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (display_id) REFERENCES displays(id)
);

CREATE TABLE hardware_sources (
	hardware_id BIGINT NOT NULL,
	sources VARCHAR(32) NULL DEFAULT NULL,
	FOREIGN KEY (hardware_id) REFERENCES hardware (id)
);

CREATE TABLE presets (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NULL DEFAULT NULL,
	hardware_id BIGINT NULL DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (hardware_id) REFERENCES hardware(id) ON UPDATE CASCADE ON DELETE CASCADE
);
	
CREATE TABLE preset_windows (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NULL DEFAULT NULL,
	source VARCHAR(32) NULL DEFAULT NULL,
	x_top_left INT NULL DEFAULT NULL,
	y_top_left INT NULL DEFAULT NULL,
	x_bottom_right INT NULL DEFAULT NULL,
	y_bottom_right INT NULL DEFAULT NULL,
	z_index INT NULL DEFAULT NULL,
	preset_id BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	FOREIGN KEY (preset_id) REFERENCES presets(id) ON UPDATE CASCADE ON DELETE CASCADE
);
